routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('welcome');
});


Route::resource('/book','BookController');

app/Models/Book.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Model;
use Illuminate\Database\Eloquent\SoftDeletes;

class Book extends Model
{
    use SoftDeletes;
    protected $primaryKey = 'bookid'; // or null
    protected $fillable= ['bookid','title','author','pbyear','genre'];
    public $incrementing = false;
}

app/User.php
<?php

namespace App;

use Illuminate\Notifications\Notifiable;
use Illuminate\Contracts\Auth\MustVerifyEmail;
use Illuminate\Foundation\Auth\User as Authenticatable;

class User extends Authenticatable
{
    use Notifiable;

    /**
     * The attributes that are mass assignable.
     *
     * @var array
     */
    protected $fillable = [
        'name', 'email', 'password',
    ];

    /**
     * The attributes that should be hidden for arrays.
     *
     * @var array
     */
    protected $hidden = [
        'password', 'remember_token',
    ];

    /**
     * The attributes that should be cast to native types.
     *
     * @var array
     */
    protected $casts = [
        'email_verified_at' => 'datetime',
    ];
}

app/Http/Controllers/BookController.php
<?php

namespace App\Http\Controllers;

use App\Models\Book;
use Illuminate\Http\Request;
use Session;

class BookController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $books = Book::all();

        return view('book.list', compact('books'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        return view ('book.create');
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        if (Book::find($request->bookid)) {
            return redirect()->back()->with('danger','Data Already Exist');
        }
        else{
            Book::create($request->all());
            return redirect()->route('book.index');
        }
    }

    /**
     * Display the specified resource.
     *
     * @param  \App\Models\Book  $book
     * @return \Illuminate\Http\Response
     */
    public function show(Book $book)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  \App\Models\Book  $book
     * @return \Illuminate\Http\Response
     */
    public function edit(Book $book)
    {
        return view ('book.edit',compact('book'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  \App\Models\Book  $book
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, Book $book)
    {
        if (Book::find($request->bookid)) {
            return redirect()->back()->with('danger','Data Already Exist');
        }
        else{
            $book->update($request->all());
            return redirect()->route('book.index');
        }
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  \App\Models\Book  $book
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        Book::find($id)->delete();
        return redirect()->route('book.index')->with('sukses','Data Berhasil Dihapus!');
    }

}

app/Http/Controllers/Controller.php
<?php

namespace App\Http\Controllers;

use Illuminate\Foundation\Bus\DispatchesJobs;
use Illuminate\Routing\Controller as BaseController;
use Illuminate\Foundation\Validation\ValidatesRequests;
use Illuminate\Foundation\Auth\Access\AuthorizesRequests;

class Controller extends BaseController
{
    use AuthorizesRequests, DispatchesJobs, ValidatesRequests;
}

resources/views/book/create.blade.php
@extends('layouts.index')

@section('judulhalaman','Create Book')

@section('isihalaman')
@if (session('danger'))
    <div class="alert alert-danger">
        {{ session('danger') }}
    </div>
@endif
<div class="row">
	<div class="col">
		<form action="{{ route('book.store') }}" method="post">
			@csrf
			<div class="form-group">
				<label>Book ID :</label>
				<input class="form-control" type="text" name="bookid" required>
			</div>
			<div class="form-group">
				<label>Title :</label>
				<input class="form-control" type="text" name="title" required>
			</div>
			<div class="form-group">
				<label>Author :</label>
				<textarea type="text" class="form-control" name="author"></textarea>
			</div>
			<div class="form-group">
				<label>Publish Year :</label>
				<textarea type="text" class="form-control" name="pbyear"></textarea>
			</div>
			<div class="form-group">
				<label>Genre :</label>
				<textarea type="text" class="form-control" name="genre"></textarea>
			</div>
			<button type="submit" class="btn btn-success">Save</button>
		</form>
	</div>
</div>
@endsection

 <script>
    var msg = '{{Session::get('alert')}}';
    var exist = '{{Session::has('alert')}}';
    if(exist){
      alert(msg);
    }
  </script>

resources/views/book/edit.blade.php
@extends('layouts.index')

@section('judulhalaman','Update Book')

@section('isihalaman')
@if (session('danger'))
    <div class="alert alert-danger">
        {{ session('danger') }}
    </div>
@endif
<div class="row">
	<div class="col">
		<form action="{{ route('book.update', $book->bookid) }}" method="post">
			@csrf
			@method('PUT')
			<div class="form-group">
				<label>Book ID :</label>
				<input class="form-control" type="text" name="bookid" value="{{$book->bookid}}" required>
			</div>
			<div class="form-group">
				<label>Title :</label>
				<input class="form-control" type="text" name="title" value="{{$book->title}}" required>
			</div>
			<div class="form-group">
				<label>Author :</label>
				<input type="text" class="form-control" name="author" value="{{$book->author}}" required>
			</div>
			<div class="form-group">
				<label>Publish Year :</label>
				<input type="text" class="form-control" name="pbyear" value="{{$book->pbyear}} " required>
			</div>
			<div class="form-group">
				<label>Genre :</label>
				<input type="text" class="form-control" name="genre" value="{{$book->genre}}" required>
			</div>
			<button type="submit" class="btn btn-success">Save</button>
		</form>
	</div>
</div>
@endsection

resources/views/book/list.blade.php
@extends('layouts.index')

@section('judulhalaman','Book List')

@section('isihalaman')
<a href="{{ route('book.create') }}" class="btn btn-secondary">
	Create Data
</a>
<div class="row">
	<div class="col">
		<table class="table table-hover">
		  <thead>
		    <tr>
		      <th scope="col">BOOK ID</th>
		      <th scope="col">Title</th>
		      <th scope="col">Author</th>
		      <th scope="col">Publishing Year</th>
		      <th scope="col">Genre</th>
		      <th scope="col">Action</th>
		    </tr>
		  </thead>
		  <tbody>
			  @foreach($books as $key => $book)
			  	@php
			  	$panjang = strlen ($book->bookid);
			  	@endphp
				  	@if($panjang == 1)
				  		@php $idnya = "KD - 0000000000" . $book->bookid; @endphp
				  	@elseif($panjang == 2)
				  		@php $idnya = "KD - 000000000" . $book->bookid; @endphp
				  	@elseif($panjang == 3)
				  		@php $idnya = "KD - 00000000" . $book->bookid; @endphp
				  	@elseif($panjang == 4)
				  		@php $idnya = "KD - 0000000" . $book->bookid; @endphp
				  	@elseif($panjang == 5)
				  		@php $idnya = "KD - 000000" . $book->bookid; @endphp
				  	@elseif($panjang == 6)
				  		@php $idnya = "KD - 00000" . $book->bookid; @endphp
				  	@elseif($panjang == 7)
				  		@php $idnya = "KD - 0000" . $book->bookid; @endphp
				  	@elseif($panjang == 8)
				  		@php $idnya = "KD - 000" . $book->bookid; @endphp
				  	@elseif($panjang == 9)
				  		@php $idnya = "KD - 00" . $book->bookid; @endphp
				  	@elseif($panjang == 10)
				  		@php $idnya = "KD - 0" . $book->bookid; @endphp
				  	@elseif($panjang == 11)
				  		@php $idnya = "KD - " . $book->bookid; @endphp
				  	@endif
			    <tr>
			      <td>{{$idnya}}</td>
			      <td>{{$book->title}}</td>
			      <td>{{$book->author}}</td>
			      <td>{{$book->pbyear}}</td>
			      <td>{{$book->genre}}</td>
			      <td>
			      	<form action="{{ route('book.destroy', $book) }}" method="post" class="form-inline">
			      		@csrf
			      		@method('DELETE')
			      		<a href="{{ route('book.edit',$book->bookid) }}" class="btn btn-secondary">
				      		Edit
				      	</a>
			      		<button type="submit" class="btn btn-danger" onclick="return confirm('Apakah anda yakin ingin menghapus data?')">Delete</button>
			      	</form>
			      </td>
			    </tr>
			   @endforeach
		  </tbody>
		</table>
	</div>
</div>
@endsection

resources/views/layouts/index.blade.php
<html>
	<head>
		<title>@yield('judulhalaman')</title>
		<link rel="stylesheet" href="{{ url('/') }}/css/app.css">
	</head>
	<body>
		<nav class="navbar navbar-light bg-light">
			<ul class="navbar-nav mr-auto mt-2 mt-lg-0">
     			<li class="nav-item active">
     				<a class="nav-link" href="#">Home</a>
     			</li>
			</ul>
		</nav>
		<div class="container">
			@yield('isihalaman')
		</div>
	</body>
</html>